version: 2
services:
  web:
    type: web
    env: python
    buildCommand: |
      apt-get update && 
      apt-get install -y libportaudio2 libportaudiocore1 portaudio19-dev python3-dev && 
      pip install --upgrade pip && 
      pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: PYTHONUNBUFFERED
        value: 1
    healthCheckPath: /
    autoDeploy: true
