services:
  - type: web
    name: screenwhisper
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: DEEPL_API_KEY
        value: "87387c27-de25-4319-b0df-facbe713070b:fx"
      - key: DEEPGRAM_API_KEY
        value: "df52f105d3f092b400678621e93d4d45fa258b71"
      - key: USE_DEEPL_PRO
        value: "false"
    ports:
      - 10000 