services:
  - type: web
    name: screenwhisper
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: DEEPL_API_KEY
        sync: false
      - key: DEEPGRAM_API_KEY
        sync: false
      - key: USE_DEEPL_PRO
        value: false 