version: 2
services:
  web:
    type: web
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PORT
        value: 8000
    healthCheckPath: /
    autoDeploy: true
